[build]
  command = "JEKYLL_ENV=production bundle exec jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.0.0"
  BUNDLE_VERSION = "2.4.22"
  NODE_VERSION = "18"

[[plugins]]
  package = "netlify-plugin-ruby"

[context.production]
  command = "JEKYLL_ENV=production bundle exec jekyll build" 